version: "3.0"
services:
  mongodb:
    entrypoint: ["/run.sh", ""]
    image: mongo
    restart: unless-stopped
    ports:
      - 27001:27001
      - 27002:27002
      - 27003:27003
      - 27004:27004
      - 27005:27005
      - 27006:27006
      - 27011:27011
      - 27012:27012
      - 27013:27013
      - 27100:27100
    volumes:
      - ./data:/data:rw
      - ./config/run.sh:/run.sh:ro
      - ./config/init.sh:/init.sh:ro
      - ./config/init-27001.txt:/init-27001.txt:ro
      - ./config/init-27004.txt:/init-27004.txt:ro
      - ./config/init-27011.txt:/init-27011.txt:ro
      - ./config/init-27100.txt:/init-27100.txt:ro
         
